FROM alpine:latest

COPY ./parallel-image-build /usr/local/bin/parallel-image-build
COPY --from=docker/buildx-bin /buildx /usr/libexec/docker/cli-plugins/docker-buildx

RUN apk add --no-cache docker-cli

ENTRYPOINT [ "/usr/local/bin/parallel-image-build" ]